# fly.toml app configuration file generated for smallweb on 2024-07-15T20:23:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "smallweb"
primary_region = "cdg"

[build]
dockerfile = 'Dockerfile'

[[mounts]]
source = 'smallweb_apps'
destination = '/home/fly'

[http_service]
internal_port = 7777

[[services]]
internal_port = 2222
protocol = "tcp"
[[services.ports]]
port = 22


[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
