# fly.toml app configuration file generated for smallweb on 2024-09-02T11:11:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smallweb'
primary_region = 'cdg'

[env]
SMALLWEB_DIR = '/home/fly/smallweb'
SMALLWEB_DOMAIN = 'example.com'
SMALLWEB_HOST = '0.0.0.0'
SMALLWEB_PORT = '8080'

[[mounts]]
source = 'smallweb'
destination = '/home/fly/smallweb'

[http_service]
internal_port = 8080

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
